project:
  type: website

website:
  title: "S11-CATS Report"
  navbar:
    left:
      - href: index.qmd
        text: Report
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



