project:
  type: website

website:
  title: "S11-CATS Report"
  navbar:
    left:
      - href: index.qmd
        text: Report
      - about.qmd
      - href: slides.qmd
        text: Slides

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true



