
# Appendix 

## Baseline scenario questionnaire {#sec-baseline-q}

### Related to data discovery {-}

- I am working for Wilmar in South East Asia. Do you know what is the forest baseline that I should use and where can I find it?
- I have been checking the results of the Soy map we created. Do you know which DEM was used for it? And where can I find it?
- Do you know which DEM is used as the terrain mask when using Sentinel 1 data?
- I need to access the concessions data provided by Grepalma. Where can I find it?

### Related to data visualization {-}

- I am interested on getting an overview of where was the primary forest present in Colombia in 2007. Could you visualize a layer with this data for me?
- I need to visualize the concessions provided by fedepalma. Could you do it for me?

## Thematic Content Analysis prompt {#sec-gpt-prompt}

```
I will give you some notes I took from an interview I did to four study subjects:
W, X, Y and Z.

Tell me if you identify any themes or topics that are repeated in the notes that 
I took from the answers of the individuals. In other words, do a simple Thematic
Content Analysis of the interviews.
```

## Code to evaluate request times {#sec-request-code}

**Disclaimer:** In order to run the code presented below, the user must have authenticated their Google account and have the TiTiler-PgSTAC and the TiTiler-Xarray services running on `localhost:8082` and `localhost:8084` respectively.

```{python}
#| echo: true
#| eval: false

import pandas as pd
import requests
import random

tiles = ["9/399/254", "10/800/505", "11/1603/1012",  "12/3209/2042", 
"13/6407/4075", "14/12817/8159", "15/25678/16271", "16/51268/32552", 
"17/102503/65134", "18/205062/130211"]

# Tiles are slightly modified to try to avoid getting cached tiles
def modify_tile(tile):
    parts = tile.split('/')
    z = int(parts[0])
    x = int(parts[1])
    y = int(parts[2])

    # Determine the range of change based on the value of z
    if z <= 9:
        change_range = 3
    elif z <= 12:
        change_range = 5
    elif z <= 15:
        change_range = 10
    elif z <= 18:
        change_range = 50

    # Apply the change to x and y
    x_change = random.randint(-change_range, change_range)
    y_change = random.randint(-change_range, change_range)

    new_x = x + x_change
    new_y = y + y_change

    # Return the modified tile as a string
    return f"{z}/{new_x}/{new_y}"

times_zarr = []
times_cog = []
z_level = []
cmap_picked = []

# The colormaps picked can be either a customized one for S11
# Forest baseline or greens_r
cmap = ["_name=greens&rescale=0,70","_name=greens_r&rescale=0,70",
        "_name=blues&rescale=0,90", "_name=blues_r&rescale=0,90",
        "_name=reds&rescale=0,80", "_name=reds_r&rescale=0,80",
        "_name=gray&rescale=0,70","_name=gray_r&rescale=0,70",
        "_name=jet&rescale=0,90", "_name=jet_r&rescale=0,90",
        "_name=hot&rescale=0,80", "_name=hot_r&rescale=0,80"]

for i in range(len(cmap)):

    mod_tiles = [modify_tile(tile) for tile in tiles]
    k = i

    for tile in mod_tiles:
        url_zarr = "http://localhost:8080/tiles/WebMercatorQuad/"+\
        f"{tile}%401x?url=gs://s11-tiles/zarr/separate&"+\
        "variable=band_data&reference=false&decode_times=true&"+\
        f"consolidated=true&colormap{cmap[k]}&return_mask=true"

        url_cog = f"http://localhost:8082/collections/"+\
        f"Example%20FBL%20Riau/items/FBL_V5_2021_Riau_cog/tiles/"+\
        f"WebMercatorQuad/{tile}%401x?bidx=1&assets=data&"+\
        "unscale=false&resampling=nearest&reproject=nearest&"+\
        f"colormap{cmap[k]}&return_mask=true"

        x = requests.get(url_zarr)
        times_zarr.append(x.elapsed.total_seconds())

        x = requests.get(url_cog)
        times_cog.append(x.elapsed.total_seconds())

        z_level.append(int(tile.split('/')[0]))

        cmap_picked.append(k)

data = pd.DataFrame([cmap_picked, z_level, times_cog, times_zarr]).T
data.columns = ['colormap','zoom level','COG', 'ZARR']

data.to_csv('request_time_results_6iter.csv')
```